#!/bin/bash

sourceDir=$(dirname $(readlink -f $0))

while(true);do
  php ${sourceDir}/combine.php
  # php ${sourceDir}/service.php
  if [ -f "${sourceDir}/tmp" ]; then
    rm -r ${sourceDir}/tmp
  fi
done

exit 0
